name: Build & Deploy

on: 
  pull_request:
    branches:
      - main

env:
  GODOT_VERSION: 4.1-stable

jobs:
  export:
    name: Export for ${{ matrix.targetPlatform.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: [
          { name: win64, path: build.exe },
          { name: html5, path: index.html }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Export Godot
        uses: ./.github/actions/godot-export
        with:
          godot-version: ${{ env.GODOT_VERSION }} 
          export-preset: ${{ matrix.targetPlatform.name }} 
          export-name: ${{ matrix.targetPlatform.path }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.targetPlatform.name }}
          path: ${{ github.workspace }}/build-${{ matrix.targetPlatform.name }}
        